version: 0.0
os: linux
files:
  - source: dist/my-angular-project
    destination: /var/www/test-AngularSite         #path on EC2
permissions:
  - object: /var/www/test-AngularSite
    pattern: '**/*'
    mode: '0755'
    owner: root
    group: root
    type: 
      - file
      - directory
hooks: 
  ApplicationStart:
    - location: deploy-scripts/application-start-hook.sh
      timeout: 300